INSERT INTO airport.user (username, password, roles) VALUES ('admin', 'nimda', 'ROLE_USER,ROLE_ADMIN');
INSERT INTO airport.medical_inspection (inspection_date, passed, pilot_id) VALUES ('2016-12-10', 1, 5);
INSERT INTO airport.medical_inspection (inspection_date, passed, pilot_id) VALUES ('2016-12-11', 1, 16);
INSERT INTO airport.medical_inspection (inspection_date, passed, pilot_id) VALUES ('2016-12-12', 1, 17);
INSERT INTO airport.medical_inspection (inspection_date, passed, pilot_id) VALUES ('2017-12-11', 0, 5);
INSERT INTO airport.medical_inspection (inspection_date, passed, pilot_id) VALUES ('2017-12-12', 1, 16);
INSERT INTO airport.medical_inspection (inspection_date, passed, pilot_id) VALUES ('2017-12-13', 1, 17);
INSERT INTO airport.medical_inspection (inspection_date, passed, pilot_id) VALUES ('2018-12-10', 1, 4);
INSERT INTO airport.medical_inspection (inspection_date, passed, pilot_id) VALUES ('2018-12-11', 0, 5);
INSERT INTO airport.medical_inspection (inspection_date, passed, pilot_id) VALUES ('2018-12-12', 0, 16);
INSERT INTO airport.medical_inspection (inspection_date, passed, pilot_id) VALUES ('2019-12-10', 1, 4);
INSERT INTO airport.medical_inspection (inspection_date, passed, pilot_id) VALUES ('2018-12-13', 1, 17);
INSERT INTO airport.medical_inspection (inspection_date, passed, pilot_id) VALUES ('2019-12-11', 0, 5);
INSERT INTO airport.medical_inspection (inspection_date, passed, pilot_id) VALUES ('2019-12-12', 1, 16);
INSERT INTO airport.medical_inspection (inspection_date, passed, pilot_id) VALUES ('2019-12-13', 1, 17);
INSERT INTO airport.medical_inspection (inspection_date, passed, pilot_id) VALUES ('2020-12-10', 1, 4);
INSERT INTO airport.medical_inspection (inspection_date, passed, pilot_id) VALUES ('2020-12-11', 1, 5);
INSERT INTO airport.medical_inspection (inspection_date, passed, pilot_id) VALUES ('2020-12-12', 1, 16);
INSERT INTO airport.medical_inspection (inspection_date, passed, pilot_id) VALUES ('2020-12-13', 1, 17);
INSERT INTO airport.flight (plane_id, takeoff, landing, type, departure_airport_id, transfer_airport_id, destination_airport_id, ticket_price, max_passengers, min_passengers, status) VALUES (1, '2021-05-19 11:45:12', '2021-05-19 15:45:18', 'DOMESTIC', 1, null, 2, 150, 10, 2, 2);
INSERT INTO airport.flight (plane_id, takeoff, landing, type, departure_airport_id, transfer_airport_id, destination_airport_id, ticket_price, max_passengers, min_passengers, status) VALUES (1, '2021-05-19 16:45:12', '2021-05-19 18:45:18', 'DOMESTIC', 2, null, 1, 150, 10, 2, null);
INSERT INTO airport.flight (plane_id, takeoff, landing, type, departure_airport_id, transfer_airport_id, destination_airport_id, ticket_price, max_passengers, min_passengers, status) VALUES (2, '2021-05-19 12:00:12', '2021-05-19 13:30:12', 'DOMESTIC', 1, null, 2, 200, 11, 2, null);
INSERT INTO airport.flight (plane_id, takeoff, landing, type, departure_airport_id, transfer_airport_id, destination_airport_id, ticket_price, max_passengers, min_passengers, status) VALUES (2, '2021-05-19 14:00:12', '2021-05-19 15:30:12', 'DOMESTIC', 2, null, 1, 200, 11, 2, null);
INSERT INTO airport.flight (plane_id, takeoff, landing, type, departure_airport_id, transfer_airport_id, destination_airport_id, ticket_price, max_passengers, min_passengers, status) VALUES (3, '2021-05-19 15:39:27', '2021-05-19 19:39:27', 'INTERNATIONAL', 1, null, 3, 300, 15, 3, 3);
INSERT INTO airport.employee (brigade, supervisor_id, department, name, surname, date_of_birth, gender, kids, sal_hour, employed_since, user_id) VALUES (null, null, 'pilots', 'King', 'Swatson', '1981-06-16', 'm', 3, 60, '2010-09-17', null);
INSERT INTO airport.employee (brigade, supervisor_id, department, name, surname, date_of_birth, gender, kids, sal_hour, employed_since, user_id) VALUES (null, null, 'technicians', 'Chen', 'Li', '1983-08-25', 'm', 2, 50, '2011-04-15', null);
INSERT INTO airport.employee (brigade, supervisor_id, department, name, surname, date_of_birth, gender, kids, sal_hour, employed_since, user_id) VALUES (null, null, 'services', 'Bonnie', 'Griffin', '1990-11-02', 'f', 2, 50, '2016-05-19', null);
INSERT INTO airport.employee (brigade, supervisor_id, department, name, surname, date_of_birth, gender, kids, sal_hour, employed_since, user_id) VALUES (1, 1, 'pilots', 'Josh', 'Peterson', '1994-02-11', 'm', 0, 30, '2018-06-13', null);
INSERT INTO airport.employee (brigade, supervisor_id, department, name, surname, date_of_birth, gender, kids, sal_hour, employed_since, user_id) VALUES (1, 1, 'pilots', 'Kate', 'Cleavland', '1992-09-15', 'f', 0, 40, '2016-10-08', null);
INSERT INTO airport.employee (brigade, supervisor_id, department, name, surname, date_of_birth, gender, kids, sal_hour, employed_since, user_id) VALUES (2, 3, 'services', 'John', 'Adams', '1995-04-20', 'm', 1, 30, '2018-03-10', null);
INSERT INTO airport.employee (brigade, supervisor_id, department, name, surname, date_of_birth, gender, kids, sal_hour, employed_since, user_id) VALUES (2, 3, 'services', 'Patsy', 'Dexter', '1993-06-13', 'f', 0, 40, '2016-01-01', null);
INSERT INTO airport.employee (brigade, supervisor_id, department, name, surname, date_of_birth, gender, kids, sal_hour, employed_since, user_id) VALUES (2, 3, 'services', 'Sara', 'Janson', '1993-06-25', 'f', 1, 35, '2017-11-29', null);
INSERT INTO airport.employee (brigade, supervisor_id, department, name, surname, date_of_birth, gender, kids, sal_hour, employed_since, user_id) VALUES (2, 3, 'services', 'Lee', 'Penner', '1990-12-12', 'f', 2, 40, '2015-03-09', null);
INSERT INTO airport.employee (brigade, supervisor_id, department, name, surname, date_of_birth, gender, kids, sal_hour, employed_since, user_id) VALUES (3, 2, 'technicians', 'Jeffrey', 'Sanford', '1989-01-02', 'm', 1, 45, '2012-06-12', null);
INSERT INTO airport.employee (brigade, supervisor_id, department, name, surname, date_of_birth, gender, kids, sal_hour, employed_since, user_id) VALUES (3, 2, 'technicians', 'Lincoln', 'Miles', '1997-04-03', 'm', 0, 28, '2019-04-16', null);
INSERT INTO airport.employee (brigade, supervisor_id, department, name, surname, date_of_birth, gender, kids, sal_hour, employed_since, user_id) VALUES (3, 2, 'technicians', 'Kev', 'Lindsay', '1991-11-11', 'm', 1, 35, '2015-03-14', null);
INSERT INTO airport.employee (brigade, supervisor_id, department, name, surname, date_of_birth, gender, kids, sal_hour, employed_since, user_id) VALUES (4, 3, 'services', 'Liz', 'Danell', '1997-04-02', 'f', 0, 30, '2019-03-18', null);
INSERT INTO airport.employee (brigade, supervisor_id, department, name, surname, date_of_birth, gender, kids, sal_hour, employed_since, user_id) VALUES (4, 3, 'services', 'Lola', 'Boon', '1989-12-03', 'f', 1, 39, '2015-05-13', null);
INSERT INTO airport.employee (brigade, supervisor_id, department, name, surname, date_of_birth, gender, kids, sal_hour, employed_since, user_id) VALUES (4, 3, 'services', 'Kira', 'Warren', '1995-11-26', 'f', 1, 37, '2017-11-01', null);
INSERT INTO airport.employee (brigade, supervisor_id, department, name, surname, date_of_birth, gender, kids, sal_hour, employed_since, user_id) VALUES (5, 1, 'pilots', 'Trina', 'Simons', '1990-05-12', 'f', 2, 40, '2016-07-03', null);
INSERT INTO airport.employee (brigade, supervisor_id, department, name, surname, date_of_birth, gender, kids, sal_hour, employed_since, user_id) VALUES (5, 1, 'pilots', 'Flint', 'Victors', '1989-03-20', 'm', 1, 40, '2016-08-10', null);
INSERT INTO airport.employee (brigade, supervisor_id, department, name, surname, date_of_birth, gender, kids, sal_hour, employed_since, user_id) VALUES (6, 2, 'technicians', 'Clint', 'Haden', '1995-07-03', 'm', 0, 30, '2019-09-23', null);
INSERT INTO airport.employee (brigade, supervisor_id, department, name, surname, date_of_birth, gender, kids, sal_hour, employed_since, user_id) VALUES (6, 2, 'technicians', 'Jordon', 'Tuft', '1996-10-09', 'm', 1, 35, '2017-10-19', null);
INSERT INTO airport.employee (brigade, supervisor_id, department, name, surname, date_of_birth, gender, kids, sal_hour, employed_since, user_id) VALUES (6, 2, 'technicians', 'Dewey', 'Emmett', '1990-08-02', 'm', 2, 40, '2013-09-10', null);
INSERT INTO airport.employee (brigade, supervisor_id, department, name, surname, date_of_birth, gender, kids, sal_hour, employed_since, user_id) VALUES (6, 2, 'technicians', 'Tommen', 'Baratheon', '1992-10-03', 'm', 0, 30, '2016-03-13', null);
INSERT INTO airport.brigade (plane_id, type) VALUES (1, 'pilots');
INSERT INTO airport.brigade (plane_id, type) VALUES (1, 'services');
INSERT INTO airport.brigade (plane_id, type) VALUES (1, 'technicians');
INSERT INTO airport.brigade (plane_id, type) VALUES (2, 'services');
INSERT INTO airport.brigade (plane_id, type) VALUES (2, 'pilots');
INSERT INTO airport.brigade (plane_id, type) VALUES (2, 'technicians');
INSERT INTO airport.flight_log (flight_id, state, time) VALUES (1, 'DELAYED DUE TO WEATHER', '2021-05-19 11:30:37');
INSERT INTO airport.flight_log (flight_id, state, time) VALUES (1, 'TAKEOFF', '2021-05-19 12:45:12');
INSERT INTO airport.flight_log (flight_id, state, time) VALUES (7, 'CANCELED DUE TO MIN PASSENGERS HASN''T BEEN ACHIEVED', '2021-05-19 15:48:35');
INSERT INTO airport.passenger (name, surname, date_of_birth, gender, user_id) VALUES ('David', 'Tyson', '1997-05-23', 'm', null);
INSERT INTO airport.passenger (name, surname, date_of_birth, gender, user_id) VALUES ('Kelly', 'Tomson', '2000-07-12', 'f', null);
INSERT INTO airport.passenger (name, surname, date_of_birth, gender, user_id) VALUES ('Peter', 'Griffin', '1998-06-17', 'm', null);
INSERT INTO airport.passenger (name, surname, date_of_birth, gender, user_id) VALUES ('Lois', 'Griffin', '1998-03-19', 'f', null);
INSERT INTO airport.passenger (name, surname, date_of_birth, gender, user_id) VALUES ('Joe', 'Swanson', '1998-04-23', 'm', null);
INSERT INTO airport.passenger (name, surname, date_of_birth, gender, user_id) VALUES ('Bonnie', 'Swanson', '1997-04-21', 'f', null);
INSERT INTO airport.plane (type, status, first_flight) VALUES ('Boeing 737', null, '2015-01-20');
INSERT INTO airport.plane (type, status, first_flight) VALUES ('Boeing 737 MAX', null, '2019-05-18');
INSERT INTO airport.plane (type, status, first_flight) VALUES ('Airbus A220', 2, '2019-07-17');
INSERT INTO airport.passenger_check (passenger_id, flight_id, check_result, time, check_name) VALUES (1, 1, 1, '2021-05-19 16:54:39', 'LUGGAGE_CHECKED_IN');
INSERT INTO airport.passenger_check (passenger_id, flight_id, check_result, time, check_name) VALUES (2, 1, 1, '2021-05-19 17:00:00', 'LUGGAGE_CHECKED_IN');
INSERT INTO airport.airport (country, city, name) VALUES ('Ukraine', 'Kyiv', 'Kyiv International Airport (Zhuliany)');
INSERT INTO airport.airport (country, city, name) VALUES ('Ukraine', 'Odessa', 'Odessa International Airport');
INSERT INTO airport.airport (country, city, name) VALUES ('England', 'London', 'Heathrow Airport');
INSERT INTO airport.airport (country, city, name) VALUES ('USA', 'New York', 'Jhon F. Kennedy International Airport');